# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taehyoungram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
